### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by ongzuchengmark** [qmss-gr5063-2019/Migration-and-Industry#2]
Hi all,

We have put up all the necessary files for the submission of our data viz final project. Thanks!

Revision SHA: 30c38d9

@tbrambor @eddiecylin @JiaxiYang1992

**Comment by tbrambor** [comment]
Comments for the Group:

This a solid effort to visualize the relationship between immigration and economic value generation. The overall website is working and all necessary elements are working but separating into tabs or subpages would help the organization. Several of the visuals are hard to read or could be improved upon. For example, the migration trend across time: why would the total population trend be needed here. Since it is plotted on the same y-axis, the migrant trends are usually not visible until population series are unselected (which is not a feature that is evident to a user). Industry value added across time: really unsure what to take away from here with respect to the immigration topic. The accompanying data table is not terribly interesting — I can’t see many users trying to finding exact values here beyond what is visible in the graph. The graph on the  relationship between migrant population and industry value added is problematic. Obviously, it is not possible to make a causal attribution here. The plotting of male and female values AND multiple values over time makes this plot cumbersome to read. 
Overall, this is a reasonable effort with significant room for improvement. 
  
Overall Grade: B
